FROM jenkins/jenkins:2.203

USER jenkins

# Set the default admin user and password
ENV JENKINS_USER admin
ENV JENKINS_PASS 1qaz2wsX

# Set log level
COPY ./bootstrap/log.properties /var/jenkins_home/log.properties

# Install plugins
COPY ./bootstrap/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

RUN echo 2 > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state && \
    echo 2 > /usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion

# Copy Jenkins groovy configuration scripts
COPY ./bootstrap/groovy /usr/share/jenkins/ref/init.groovy.d/
