FROM jenkinsci/jnlp-slave

USER root

WORKDIR /opt

# Install utilities

RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y unzip
RUN apt-get install -y lsb-release
RUN apt-get install -y gnupg
RUN apt-get install -y curl
RUN apt-get install -y make

# Install terraform
ENV TERRAFORM_VERSION=0.11.10

RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
RUN unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
RUN mv terraform /usr/bin/

# Install gcloud sdk
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && apt-get install google-cloud-sdk -y

# Install Kubectl
RUN apt-get install -y kubectl

#Install Utilities
RUN apt-get update; \
    apt-get install -y vim; \
    apt-get install -y iputils-ping; \
    apt-get install -y gettext-base; \
    apt-get install -y dnsutils; \
    apt-get install -y postgresql-client

# Install Helm
RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh

# Install docker
RUN wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.2.tgz
RUN tar -xzf docker-19.03.2.tgz
RUN mv ./docker/* /usr/bin

# Install docker compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

# Install node
RUN curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh; \
    bash nodesource_setup.sh; \
    apt-get install -y nodejs; \
    npm install -g npm@7.20.3

RUN npm install -g yarn

ENTRYPOINT ["jenkins-slave"]